/* Stockfish 19 Lite single-threaded; local WASM, no server analysis required. */
(()=>{
  const path='engines/stockfish-19-lite-single.js';
  class Engine{
    constructor(){this.queue=Promise.resolve();this.worker=null;this.pending=null;this.ready=null}
    boot(){if(this.ready)return this.ready;this.ready=new Promise((resolve,reject)=>{this.worker=new Worker(path);const timeout=setTimeout(()=>reject(Error('טעינת המנוע התעכבה')),20000);this.worker.onerror=()=>{clearTimeout(timeout);reject(Error('טעינת Stockfish 19 נכשלה'))};this.worker.onmessage=e=>{for(const line of String(e.data).split('\n')){if(line.trim()==='uciok'){clearTimeout(timeout);this.worker.postMessage('setoption name Hash value 32');resolve()}const p=this.pending;if(!p)continue;const score=line.match(/score (cp|mate) (-?\d+)/),pv=line.match(/ pv (.+)/),number=line.match(/multipv (\d+)/);if(score&&pv&&!/upperbound|lowerbound/.test(line)){const mate=score[1]==='mate'?+score[2]:null;const depth=+(line.match(/depth (\d+)/)?.[1]||0);p.depths[depth]??=[];p.lines=p.depths[depth];p.lines[(number?+number[1]:1)-1]={score:mate===null?+score[2]:Math.sign(mate)*100000,mate,pv:pv[1].trim().split(/\s+/)};}if(line.startsWith('bestmove ')){this.pending=null;const complete=Object.entries(p.depths).filter(([,rows])=>rows.filter(Boolean).length>=p.expected&&new Set(rows.filter(Boolean).map(r=>r.pv[0])).size>=p.expected).sort((a,b)=>+b[0]-+a[0])[0]?.[1]||p.lines;p.resolve({...complete[0],best:line.split(/\s+/)[1],lines:complete.filter(Boolean).filter((r,i,rows)=>rows.findIndex(x=>x.pv[0]===r.pv[0])===i)})}}};this.worker.postMessage('uci')});return this.ready}
    search(fen,{lines=1,time=1000,skill=20,depth=null}={}){const task=this.queue.then(async()=>{const pos=new Chess(fen);if(pos.isGameOver())return {score:pos.isCheckmate()?-100000:0,mate:pos.isCheckmate()?0:null,best:null,pv:[],lines:[]};await this.boot();return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{this.worker.terminate();this.ready=null;this.pending=null;reject(Error('זמן החיפוש הסתיים'))},30000);this.pending={lines:[],depths:{},expected:Math.min(lines,pos.moves().length),resolve:r=>{clearTimeout(timeout);resolve(r)}};this.worker.postMessage('setoption name Skill Level value '+skill);this.worker.postMessage('setoption name MultiPV value '+Math.max(1,Math.min(5,lines)));this.worker.postMessage('position fen '+fen);this.worker.postMessage(depth?'go depth '+depth:'go movetime '+time)})});this.queue=task.catch(()=>{});return task}
  }
  const analysis=new Engine(),player=new Engine(),hints=new Engine();window.ChessAnalysis={search:(fen,options)=>analysis.search(fen,options),Engine,name:'Stockfish 19 Lite'};
  evaluate=fen=>analysis.search(fen,{time:1000});
  computerMove=(fen,level)=>player.search(fen,{skill:level,time:150+level*35});
  // Keep the hint API used by game-hints, but supply the modern worker.
  bootPlayer=async()=>{await hints.boot();playerWorker=hints.worker;playerWorker.onmessage=e=>{for(const line of String(e.data).split('\n')){if(!playerPending)continue;const info=line.match(/score (cp|mate) (-?\d+).*?pv (.+)/);if(info&&!/upperbound|lowerbound/.test(line)){playerPending.score=info[1]==='cp'?+info[2]:Math.sign(+info[2])*100000;playerPending.mate=info[1]==='mate'?+info[2]:null;playerPending.pv=info[3].trim().split(/\s+/)}if(line.startsWith('bestmove ')){const result=playerPending;playerPending=null;result.resolve({score:result.score||0,mate:result.mate,pv:result.pv||[],best:line.split(' ')[1]})}}};};
})();
