(()=>{
  const $=id=>document.getElementById(id);
  const style=document.createElement('style');style.textContent=`.game{width:min(100%,calc(100svh - 200px))}#liveAdvantage{height:62px;margin-top:5px;background:#262421;border-radius:7px;padding:4px 8px;font-size:11px}#liveAdvantage svg{width:100%;height:35px;display:block}#trainingReview{position:fixed;inset:4vh 3vw;z-index:40;overflow:auto;background:#262421;border:1px solid #769656;border-radius:14px;padding:18px;direction:rtl;color:#f2f1ed}#trainingReview[hidden]{display:none}#trainingReview button{background:#577b39;border:0;color:white;border-radius:6px;padding:9px;margin:3px;cursor:pointer}#trainingReview select{width:auto}#trainingReview .metrics{display:flex;flex-wrap:wrap;gap:12px}#trainingReview table{width:100%;border-collapse:collapse;font-size:13px}#trainingReview td,#trainingReview th{padding:7px;border-bottom:1px solid #46433d;text-align:right}#trainingReview .review-actions{position:sticky;top:0;background:#262421;padding:5px}#reviewBoardOverlay{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:4}#board{position:relative}#practiceBanner{background:#263120;padding:7px;border-radius:6px;font-size:12px}`;document.head.append(style);
  const live=document.createElement('section');live.id='liveAdvantage';live.innerHTML='<span id="liveEval">יתרון המנוע · ממתין לחישוב</span><svg viewBox="0 0 400 40" role="img" aria-label="גרף יתרון חי"></svg>';$('yourColor').closest('.game').append(live);
  const panel=document.createElement('section');panel.id='trainingReview';panel.hidden=true;panel.innerHTML='<div class="review-actions"><button id="closeTraining">חזרה ללוח</button><button id="keyPrev">רגע קודם</button><button id="keyNext">רגע חשוב הבא</button><button id="practiceMistake">נסה שוב מהעמדה</button><button id="visualizeIdea">הצג רעיון ואיומים</button><button id="playVariation">נגן המשך</button><label><input type="checkbox" id="coachVoice"> הדרכה קולית</label><label>קצב <select id="variationSpeed"><option value="1500">רגיל</option><option value="3000">איטי</option><option value="800">מהיר</option></select></label></div><h2>סקירת המשחק והמאמן</h2><p id="trainingOpening"></p><div id="trainingMetrics" class="metrics"></div><p id="trainingLesson"></p><p id="trainingSkills"></p><p style="font-size:12px">דיוק, דירוג וסיווגים הם הערכות מקומיות. מבריק, נהדר ופספוס מבוססים על כללים מקורבים; זיהוי הפתיחה מוגבל לפתיחות המוכרות למאגר המקומי.</p><table><thead><tr><th>מסע</th><th>מהלך</th><th>סיווג</th><th>אובדן</th><th>המלצה</th></tr></thead><tbody id="trainingRows"></tbody></table>';
  document.body.append(panel);
  const open=document.createElement('button');open.textContent='סקירה מלאה ותרגול';open.id='openTrainingReview';open.style.cssText='width:100%;padding:7px;border:0;border-radius:6px;background:#577b39;color:white;margin-top:5px';$('reviewButton').after(open);
  let worker=null,ready=null,waiter=null,queue=Promise.resolve(),liveKey='',liveVersion=0,active=0,retry=null,animation=0;const cache=new Map(),evaluations=new Map();
  function boot(){if(ready)return ready;ready=new Promise((resolve,reject)=>{worker=new Worker('stockfish-puzzle-engine.js');const timer=setTimeout(()=>reject(Error('המנוע לא נטען')),20000);worker.onerror=()=>{clearTimeout(timer);reject(Error('שגיאת מנוע'))};worker.onmessage=e=>{const line=String(e.data);if(line==='uciok'){clearTimeout(timer);worker.postMessage('setoption name Skill Level value 20');resolve()}else if(waiter){const m=line.match(/score (cp|mate) (-?\d+)/);if(m&&!/upperbound|lowerbound/.test(line)){waiter.score=m[1]==='cp'?+m[2]:Math.sign(+m[2])*100000;waiter.mate=m[1]==='mate'?+m[2]:null}const pv=line.match(/ pv (.+)/);if(pv)waiter.pv=pv[1].split(' ');if(line.startsWith('bestmove ')){const p=waiter;waiter=null;p.resolve({score:p.score||0,mate:p.mate,best:line.split(' ')[1],pv:p.pv||[]})}}};worker.postMessage('uci')});return ready}
  function assess(fen){if(cache.has(fen))return cache.get(fen);const p=window.ChessAnalysis.search(fen,{time:700});cache.set(fen,p);p.catch(()=>cache.delete(fen));return p}
  function plot(){const moves=game.history({verbose:true});const points=moves.map((m,i)=>{const v=evaluations.get(m.after);return v===undefined?null:`${i*400/Math.max(1,moves.length-1)},${20-Math.max(-8,Math.min(8,v))*2.2}`}).filter(Boolean).join(' ');live.querySelector('svg').innerHTML='<line x1="0" y1="20" x2="400" y2="20" stroke="#777" stroke-dasharray="3"/><polyline points="'+points+'" stroke="#c7e39e" stroke-width="2" fill="none"/>'}
  async function updateLive(){const fen=game.fen();if(fen===liveKey)return;liveKey=fen;const version=++liveVersion;try{const result=await assess(fen);const white=result.score*(fen.split(' ')[1]==='w'?1:-1)/100;evaluations.set(fen,white);plot();if(version===liveVersion){const pos=new Chess(fen);$('liveEval').textContent=pos.isCheckmate()?'שח־מט':pos.isDraw()?'תיקו':result.mate!==null&&result.mate!==undefined?'M'+Math.abs(result.mate)+' · מט ב־'+Math.abs(result.mate):'יתרון: '+(white>0?'לבן +':white<0?'שחור +':'שוויון ')+Math.abs(white).toFixed(2)+' · Stockfish 19 Lite'}}catch{if(version===liveVersion)$('liveEval').textContent='גרף היתרון לא זמין כרגע'}}
  function opening(){const s=game.history().slice(0,6).join(' ');const known=[['e4 e5 Nf3 Nc6 Bb5','הפתיחה הספרדית','פתח כלים והכן הצרחה.'],['e4 e5 Nf3 Nc6 Bc4','הפתיחה האיטלקית','בדוק את f7 ואת המרכז.'],['e4 c5','ההגנה הסיציליאנית','שלוט במרכז והיזהר מפיגור בפיתוח.'],['e4 e6','ההגנה הצרפתית','שמור על מרכז הרגלים ופתח את הרץ.'],['e4 c6','קארו־קאן','פתח כלים לפני מסעי רגלים נוספים.'],['d4 d5 c4','גמביט המלכה','לחץ על המרכז ושמור על פיתוח.'],['d4','פתיחת רגלי המלכה','פתח פרשים ורצים והצרח מוקדם.'],['e4','פתיחת רגלי המלך','התמקד בפיתוח ובבטיחות המלך.']];return known.find(x=>s.startsWith(x[0]))?.slice(1)||['פתיחה לא מזוהה במאגר המקומי','תרגול מומלץ: פיתוח כלים, שליטה במרכז ובטיחות המלך.']}
  function kind(row,i){const moves=game.history({verbose:true}),m=moves[i];if(i<6&&row.loss<50&&opening()[0]!=='פתיחה לא מזוהה במאגר המקומי')return 'תיאורטי (משוער)';if(row.loss>=200)return 'שגיאה חמורה';if(row.loss>=100)return row.line?.includes('#')?'פספוס מט':'שגיאה';if(row.loss>=50)return 'אי־דיוק';if(row.label==='המהלך המומלץ'){const after=new Chess(m.after),value={p:1,n:3,b:3,r:5,q:9,k:0};const exposed=after.board().flat().filter(Boolean).some(p=>p.color===m.color&&value[p.type]>=3&&after.isAttacked(p.square,m.color==='w'?'b':'w'));return exposed&&m.piece!=='p'?'הקרבה מומלצת (מבריק משוער)':Math.abs(row.eval)>2&&i>0&&Math.abs(reviewRows[i-1].eval)<1?'נהדר (משוער)':'הטוב ביותר'}return row.loss<20?'מצוין':'טוב'}
  function speak(text){if(!$('coachVoice').checked||!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='he-IL';speechSynthesis.speak(u)}
  function focusRow(i){active=Math.max(0,Math.min(reviewRows.length-1,i));reviewIndex=active;drawReview();$('trainingLesson').textContent=reviewRows[active].explanation+' ההמשך: '+reviewRows[active].line;speak($('trainingLesson').textContent)}
  function summary(){const [name,plan]=opening();$('trainingOpening').textContent=name+' · '+plan;$('trainingMetrics').replaceChildren();for(const color of ['w','b']){const rows=reviewRows.filter(r=>r.color===color),accuracy=rows.length?Math.round(rows.reduce((s,r)=>s+100*Math.exp(-r.loss/180),0)/rows.length):0;const rating=Math.round((600+accuracy*18)/100)*100;const p=document.createElement('p');p.textContent=`${color==='w'?'לבן':'שחור'}: דיוק משוער ${accuracy}% · ביצוע משוער ${rating} · ${rows.filter(r=>r.loss>=100).length} שגיאות`;$('trainingMetrics').append(p)}$('trainingRows').replaceChildren();reviewRows.forEach((r,i)=>{const tr=document.createElement('tr');for(const value of [Math.floor(i/2)+1+(r.color==='w'?'.':'…'),r.san,kind(r,i),(r.loss/100).toFixed(2),r.bestSan]){const td=document.createElement('td');td.textContent=value;tr.append(td)}tr.style.cursor='pointer';tr.onclick=()=>focusRow(i);$('trainingRows').append(tr)});const own=reviewRows.filter(r=>r.color===playerColor),errors=own.filter(r=>r.loss>=100).length;let skills={games:0,moves:0,good:0};try{skills=JSON.parse(localStorage.getItem('chess-training-skills')||'null')||skills;const key=game.pgn();if(localStorage.getItem('chess-training-last')!==key){skills.games++;skills.moves+=own.length;skills.good+=own.filter(r=>r.loss<50).length;localStorage.setItem('chess-training-skills',JSON.stringify(skills));localStorage.setItem('chess-training-last',key)}}catch{}$('trainingSkills').textContent=`מעקב מקומי: ${skills.games} משחקים נותחו · ${skills.good} / ${skills.moves} מהלכים טובים. מוקד לתרגול: ${errors?'בדיקת שחים, הכאות ואיומים לפני המהלך':'שמירה על דיוק ופיתוח כלים'}.`;focusRow(0)}
  open.onclick=async()=>{if(reviewBusy||playBusy)return;panel.hidden=false;$('trainingLesson').textContent='מנתח את המשחק…';try{await $('reviewButton').onclick();if(reviewRows.length)summary();else $('trainingLesson').textContent='אין מהלכים לניתוח.'}catch{$('trainingLesson').textContent='הניתוח לא הושלם.'}};
  $('closeTraining').onclick=()=>{panel.hidden=true};
  function jump(direction){let i=active+direction;while(i>=0&&i<reviewRows.length&&reviewRows[i].loss<50)i+=direction;if(i>=0&&i<reviewRows.length)focusRow(i)}$('keyPrev').onclick=()=>jump(-1);$('keyNext').onclick=()=>jump(1);
  const normalClick=clickSquare;clickSquare=sq=>{if(!retry)return normalClick(sq);const p=retry.pos.get(sq);if(p&&p.color===retry.pos.turn()){retry.selected=sq;return}if(!retry.selected)return;try{const m=retry.pos.move({from:retry.selected,to:sq,promotion:'q'});if(m.from+m.to+(m.promotion||'')===retry.best){$('practiceBanner').textContent='נכון! מצאת את המלצת המנוע.';reviewPosition=retry.pos;retry=null;render()}else{retry.pos.undo();retry.selected=null;$('practiceBanner').textContent='יש מהלך טוב יותר. בדוק שח, הכאות ואיומים.'}}catch{retry.selected=null}};
  const banner=document.createElement('div');banner.id='practiceBanner';banner.hidden=true;live.after(banner);$('practiceMistake').onclick=()=>{const r=reviewRows[active];if(!r)return;retry={pos:new Chess(r.before),best:r.best,selected:null};reviewPosition=retry.pos;banner.hidden=false;banner.textContent='תרגול: בחר כלי ומשבצת כדי למצוא את המהלך הטוב ביותר.';panel.hidden=true;render()};
  const cancelPractice=document.createElement('button');cancelPractice.textContent='חזרה למשחק החי';cancelPractice.onclick=()=>{animation++;retry=null;banner.hidden=true;reviewPosition=null;render();schedule()};banner.after(cancelPractice);cancelPractice.style.cssText='border:0;border-radius:5px;background:#46433d;color:white;font-size:11px';
  function arrow(from,to,color){const svg=$('reviewBoardOverlay')||(()=>{const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.id='reviewBoardOverlay';s.setAttribute('viewBox','0 0 800 800');board.append(s);return s})();const xy=s=>{let x='abcdefgh'.indexOf(s[0]),y=8-Number(s[1]);if(flipped){x=7-x;y=7-y}return [x*100+50,y*100+50]};const a=xy(from),b=xy(to);const line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v]of Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:color,'stroke-width':13,'stroke-linecap':'round'}))line.setAttribute(k,v);svg.append(line);const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',b[0]);circle.setAttribute('cy',b[1]);circle.setAttribute('r',18);circle.setAttribute('fill',color);svg.append(circle)}
  $('visualizeIdea').onclick=()=>{const r=reviewRows[active];if(!r)return;focusRow(active);panel.hidden=true;arrow(r.best.slice(0,2),r.best.slice(2,4),'#f5bb42');const pos=new Chess(r.before);try{const m=pos.move(moveFromUci(r.best));const opponent=m.color==='w'?'b':'w';for(const piece of pos.board().flat().filter(Boolean)){if(piece.color===opponent&&pos.isAttacked(piece.square,m.color))arrow(piece.square,piece.square,'#e66363')}banner.hidden=false;banner.textContent='זהב: המהלך המומלץ. נקודות אדומות: כלים המאוימים בעמדה שאחרי המהלך.'}catch{}};
  $('playVariation').onclick=async()=>{const r=reviewRows[active];if(!r)return;const token=++animation;panel.hidden=true;const pos=new Chess(r.before);for(const san of (r.line||'').split(' → ').filter(Boolean)){if(token!==animation)return;try{pos.move(san);reviewPosition=pos;render()}catch{break}await new Promise(resolve=>setTimeout(resolve,+$('variationSpeed').value))}banner.hidden=false;banner.textContent='סיום ההמשך המוצע. חזור למשחק או פתח סקירה.'};
  for(const id of ['reset','undo','exitReview'])$(id).addEventListener('click',()=>{animation++;retry=null;banner.hidden=true});
  new MutationObserver(updateLive).observe(board,{childList:true});updateLive();
})();
